### ISSUE TITLE
Cadastrar funcional do promoter

### ISSUE THREAD

**Issue by Linkyed** [WilburTicketsCode/backend#117]
Fazer com que o cadastro do promoter seja funcional de verdade agora.

Usar a pagina de cadastro de promoter e usar o POST da API do promoter para fazer o cadastro no banco de dados.

Na pasta /tutorial/como-cadastra tem um exemplo de codigo de como mandar o POST para API e assim concluir o cadastro.

Formato de JSON aceitado pela API:
{
cpf: promoter.cpf,
cnpj: promoter.cpnj,
status: promoter.status,
data_nasc: promoter.data_nasc,
telefone: promoter.telefone,
usuario: {
nome: promoter.nome,
email: promoter.email,
senha: promoter.password
},
endereco: {
rua: promoter.rua,
numero: promoter.numero,
bairro: promoter.bairro,
cidade: promoter.cidade,
estado: promoter.estado,
cep: promoter.cep,
complemento: promoter.complemento,
}
}

**Comment by Vanderleicio** [comment]
@fernandocintra2871
