### ISSUE TITLE
Cadastrar funcional do cliente

### ISSUE THREAD

**Issue by Linkyed** [WilburTicketsCode/backend#118]
Fazer com que o cadastro do cliente seja funcional de verdade agora.

Usar a pagina de cadastro de cliente e usar o POST da API do cliente para fazer o cadastro no banco de dados.

Na pasta /tutorial/como-cadastra tem um exemplo de codigo de como mandar o POST para API e assim concluir o cadastro.

Formato de JSON aceitado pela API:
(Com cartão)
{
cpf: cliente.cpf,
telefone: cliente.telefone,
data_nasc: cliente.data_nasc,
usuario: {
nome: cliente.nome,
email: cliente.email,
senha: cliente.password
},
endereco: {
rua: cliente.rua,
numero: cliente.numero,
bairro: cliente.bairro,
cidade: cliente.cidade,
estado: cliente.estado,
cep: cliente.cep,
complemento: cliente.complemento,
},
cartao: {
num_cartao: cliente.num_cartao,
dono_cartao: cliente.dono_cartao,
data_vencimento: cliente.data_vencimento,
cvv: cliente.cvv,
}
}

OU

(Sem cartão)
{
cpf: cliente.cpf,
telefone: cliente.telefone,
data_nasc: cliente.data_nasc,
usuario: {
nome: cliente.nome,
email: cliente.email,
senha: cliente.password
},
endereco: {
rua: cliente.rua,
numero: cliente.numero,
bairro: cliente.bairro,
cidade: cliente.cidade,
estado: cliente.estado,
cep: cliente.cep,
complemento: cliente.complemento,
},
cartao: null
}

**Comment by Vanderleicio** [comment]
@fernandocintra2871
