### ISSUE TITLE
Ocultar senha nas respostas da api

### ISSUE THREAD

**Issue by wlfoj** [WilburTicketsCode/backend#181]
A senha e outros dados estão sendo retornado quando se busca informações de um usuário, a senha não deve ser exibida.
Cria uma estrutura de resposta que contenha apenas os dados necessários, como um **dto**.

**Comment by Linkyed** [comment]
Feito, agora nenhuma das api's relacionadas aos usuários do sistema retornam a senha dos respectivos tipos de usuário
