### ISSUE TITLE
Endpoint par alterar senha

### ISSUE THREAD

**Issue by wlfoj** [WilburTicketsCode/backend#182]
O endpoint deverá receber o id do usuário, a senha atual e a nova. Deverá ser feita uma busca no banco para verificar a existência de um user com o id e a senha fornecida. 

- Se existe um user com os dados passados, a senha será alterada.
- Se não existir, uma mensagem de erro ou exceção é lançada.

**Comment by Linkyed** [comment]
Feito, porem usada uma logica diferente, para alterar um dado na API de usuário é necessário usar o seu e-mail, o novo dado e o tipo de alteração, assim deixando a função mais genérica e podendo atender a possíveis outras alterações e não só a alteração de senha.

Então para alterar a senha, é necessário de usar o e-mail do usuário (que ja estaria disponível na sessão do nextauth que ele esta logado), a nova senha dele e o tipo de alteração que nesse caso é a string 'trocar senha'. A verificação da senha antiga já poder ser feita pela API de login, então na pagina de alterar senha, a verificação da senha atual é feita com a api de login, e assim que confirmado a alteração de senha pode ser feita com a api de usuário

Para os casos de que o usuário digite a antiga senha errado, o 'ERROR 03' é retornado pela API.

Exemplo feito usando a API esta no arquivo /app/tutorial/como-alterar/page.tsx
