### ISSUE TITLE
Listagem de eventos suspensos e ativos [ADM e PROMOTER]

### ISSUE THREAD

**Issue by WagnerAlexandre** [WilburTicketsCode/backend#215]
Separar em duas telas diferentes ou modificar as existentes para exibir eventos suspensos em "cinza"

**Comment by igoxy** [comment]
![suspender](https://github.com/WilburTicketsCode/backend/assets/83670525/426a4f23-e1f7-4b40-887a-a5cb5bc612f5)


Pode ser assim?

Nessa parte ai tem que tratar o botão de excluir evento que não tá fazendo nada, mas não fui eu quem fiz, então nem mexi. Só fiz o botão de suspender evento desaparecer, caso o evento seja suspenso.
