### ISSUE TITLE
Disponibilizar endpoint para atualização de dados de promoter

### ISSUE THREAD

**Issue by wlfoj** [WilburTicketsCode/backend#220]
O endpoint deverá receber todos os dados do usuário e atualizar tudo de uma vez. Utilize o **TRECHO ADEQUADO** presente em lib/usuario.ts para se basear. Verifique também a alteração feita /api/usuario/alterar-senha.

- Requisição de tipo PUT.
- Utilizar as respostas com o **STATUS HTTP** coerente.
- Todos os dados do usuário devem estar no body, exceto o identificador que deverá ir na URL.
- !! Não deve haver seleção de tipo para update, todos os dados recebidos no body deverão ser atualizados.

**Comment by wlfoj** [comment]
Dados enviados no body da requisição:
{
    cpf: string,
    endereco:{ 
        bairro: string, 
        cep: string, 
        cidade: string, 
        complemento: string, 
        estado: string, 
        numero: string, 
        rua: string
    },
    telefone: string,
    usuario: {
        nome: string, 
        email: string
    }
}

**Comment by Linkyed** [comment]
[](https://github.com/WilburTicketsCode/backend/commit/c40ad2c05a96af3feeabe78e493f292ab00ae034)

[](https://github.com/WilburTicketsCode/backend/commit/d2bfedf674d9a6c0f897630373621cb802cf5fc1)

Feito, o body enviado possui mais atributos pois o que está na issue não tem todos os atributos que podem ser alterados do promoter, como o status dele e data de nascimento, e tambem o promoter pode ou não t er cpf, pois ele fica limitado a ter o cpf ou cpnj, então o atributo cpf ficou cpfORcpnj, porem acho que não tem porque ele esta ai porque a gente decidiu nunca deixar editar dados que possuem unique, mas ta lá no codigo.

**Comment by wlfoj** [comment]
Não deve haver status nem a data de nascimento.

**Comment by Linkyed** [comment]
Alterações feitas
