### ISSUE TITLE
Refazer o preenchimento de dados no banco (seed)

### ISSUE THREAD

**Issue by wlfoj** [WilburTicketsCode/backend#230]
Observar erros de formatação, tipos e tamanhos.

**Comment by wlfoj** [comment]
- [ ] O número do endereço deve ser uma string
- [ ] O telefone deve ter tamanho 11 caracteres (apenas números)
- [ ] Os dados de cpf, cnpj, cep e telefone devem ser persistidos apenas os números

**Comment by Linkyed** [comment]
`https://github.com/WilburTicketsCode/backend/commit/6caa16de7deee68ccec6d25bbbf68f85fd311e7f`

Feito

**Comment by wlfoj** [comment]
Dados continuam com erro
- promoter tostinha123@yahoo.com tem o número da residência como tipo número ainda.
